### ISSUE TITLE
Task 2.2: Photomosaic of a Sunken Subway Car

### ISSUE THREAD

**Issue by ShrimpCryptid** [uwrov/2018-2019#6]
- [ ] Assemble subway car prop
- [x] Identify white rectangles (with tape) in an image.
- [x] Isolate largest rectangle in the image.
- [x] Transform image so that the rectangle is squared (remove any rotation/perspective shift).
- [x] Save the image.
- [x] Allow for capture several different rectangles, one after another.
- [ ] Display all the saved images in the diagram correctly.
- [ ] Code review w/ Peyton & Margot

**Comment by WolfboxW** [comment]
https://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example/

I found this tutorial for the transformation piece that might be really helpful.

You can use the techniques outlined here (https://www.pyimagesearch.com/2016/02/08/opencv-shape-detection/) to locate shapes (rectangles) in the file. I can walk through this on Wednesday for you too, if it's helpful.
